### ISSUE TITLE
I get an error message when trying to run this script!!

### ISSUE THREAD

**Issue by ebamgithub** [odysseyjacob/costco-scrape#1]
I get an error message when trying to run this script!!

**Comment by odysseyjacob** [comment]
Please elaborate on the issue...

**Comment by ebamgithub** [comment]
Ok will elaborate, and try to post a screenshot of the message if that helps...(give me a couple of hours).

**Comment by ebamgithub** [comment]
I decided the best way to explain is to say Bs4 isn't working and I will upload a video here of me trying to run the script ( as I am a bit of a noob).

https://youtu.be/wzqPnY5oV18

Here is the link to the video screenshot of me trying to operate it,

**Comment by ebamgithub** [comment]
Actually I got selenium running Now:

I get Traceback (most recent call last):
  File "C:\Users\ebam_\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\ebam_\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ebam_\AppData\Local\Programs\Python\Python36-32\EB-test-scripts\costco-scrape-master\costco-scrape-master\scrape.py", line 153, in run
    load_data(driver)
  File "C:\Users\ebam_\AppData\Local\Programs\Python\Python36-32\EB-test-scripts\costco-scrape-master\costco-scrape-master\scrape.py", line 43, in load_data
    extract_and_load_all_data(soup)
  File "C:\Users\ebam_\AppData\Local\Programs\Python\Python36-32\EB-test-scripts\costco-scrape-master\costco-scrape-master\scrape.py", line 130, in extract_and_load_all_data
    "Meta tags": get_meta_tags(soup),
  File "C:\Users\ebam_\AppData\Local\Programs\Python\Python36-32\EB-test-scripts\costco-scrape-master\costco-scrape-master\scrape.py", line 61, in get_meta_tags
    meta_tags = [tags.get('name') + " is " + tags.get('content') for tags in soup.find_all('meta')[3:8]]
  File "C:\Users\ebam_\AppData\Local\Programs\Python\Python36-32\EB-test-scripts\costco-scrape-master\costco-scrape-master\scrape.py", line 61, in <listcomp>
    meta_tags = [tags.get('name') + " is " + tags.get('content') for tags in soup.find_all('meta')[3:8]]
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

as an error message. I will upload the second video of my correction ( i was making a mistake when running the file initially as shown in the first video...

( This is the actual error i had yesterday).

**Comment by ebamgithub** [comment]
![screenshot error](https://user-images.githubusercontent.com/38590466/53849193-f3e15100-3fae-11e9-9cf1-702a74c8473a.JPG)

https://youtu.be/QonhNDoU2e0

here is the video of me attempting it, as we can see selenium loads but some error occurs.

**Comment by odysseyjacob** [comment]
Costco most likely changed the format of their website since I last wrote the code. This completely breaks the script.

**Comment by ebamgithub** [comment]
When exactly did you write this script and what is the logic behind it so I can rewrite it and get a scraper , ideally for me I want to know how to rewrite it so it’s workable as I want to know how to build a similar scraper for different website ( the overall logic is what I am interested in).

Emmanuel

Sent from my iPhone

On 6 Mar 2019, at 01:44, Jacob Chudnovsky <notifications@github.com<mailto:notifications@github.com>> wrote:


Costco most likely changed the format of their website since I last wrote the code. This completely breaks the script.

**Comment by odysseyjacob** [comment]
I finished writing it Jul 16, 2018. The logic is simply to use Selenium as a webdriver, and then use beautifulsoup to access the html tags of the page for the exact values that you want (will differ for every page). Thats it!

**Comment by ebamgithub** [comment]
U made it sound so simple to make!

________________________________

**Comment by ebamgithub** [comment]
Hmmn I am struggling with this, do you use skype or discord or telegram and you could give me some hints about how to update the code coming from the perspective that I am a bit of a noob.
